### ISSUE TITLE
Can't build from alpine:latest

### ISSUE THREAD

**Issue by mjo09a** [jdrago999/aws-cli-on-CoreOS#4]
Building from alpine latest fails. Here is the error.
ERROR: unsatisfiable constraints:
  py-pip (virtual):
    provided by: py2-pip
    required by: world[py-pip]
The command '/bin/sh -c apk add --update     python     py-pip &&     adduser -D aws' returned a non-zero code: 1 

If I build from alpine:3.4 it works.

**Comment by jdrago999** [comment]
Thanks for the report -- I'll get on this later today.
