### ISSUE TITLE
Docker image not building

### ISSUE THREAD

**Issue by acron0** [jdrago999/aws-cli-on-CoreOS#8]
Our CI started complaining this morning with 
```
docker: Tag latest not found in repository docker.io/jdrago999/aws-cli.`
```

Turns out there's an issue on Docker Hub: https://hub.docker.com/r/jdrago999/aws-cli/builds/b5sremvrd4drzo9ocsjxjal/

It looks like your syntax fix was never pushed to Docker hub?

**Comment by jdrago999** [comment]
Wow - I'm getting to this really late.

I'll fix the Docker Hub image to automatically build from updates here.
